development.md
index.md
xl_troubleshooting.md

Noticed there were a fair few questions that kept popping up in #dev, so I figured I'd answer those as well as some of the questions I had when I initially arrived.

Add development FAQ

---

development.md

Came up on the Discord so I figured I'd answer it

development: Add a FAQ about debugging

---

xl_troubleshooting.md

REF: https://discord.com/channels/581875019861328007/584827243617058816/850037529922371604

Add edge case about Fedora TLS settings

---

development.md

- Minor language tweaks to improve the quality of the prose
- Removing Kara's getting-started guide as it's currently unmaintained
- Mentioned ILRepack for client structs
- Added a FAQ about the .NET 5 upgrade
- Quoted goat's explanation about why certain plugins are disallowed to make it clearer who's speaking (hope this is a reasonable liberty to take!)
- Some other minor tweaks here and there

Update development FAQ with recent changes

---

development.md

goats operate on octal, so the 8th is actually the 10th

development: remove temporary D6 info

---

xl_troubleshooting.md

Let me know if we need more/less/different information before we merge this, because I'm listing out all known non-FFXIV networks.

Security FAQ updates

---

development.md

Replace code block with a list of links to the relevant classes for the services

literally just thought of this as you merged it

---

development.md

Winter linked to this so I'm adding it to the FAQ before we collectively forget

Add map coordinates FAQ

---

mobile_otp.md

Clarifies `XL Authenticator` where necessary.

Clarification

---

steamdeck.md

This page is not linked to from anywhere, currently.

Add basic Steam Deck installation guide

---

xl_troubleshooting.md

xl_troubleshooting: fix line breaks

---

xl_troubleshooting.md

xl_troubleshooting: fix antivirus capitalization

---

dalamud_troubleshooting.md

add ocean fishin

---

dalamud_troubleshooting.md

Seems to be working as expected now from discord chats.

remove fcnamecolor

---

steamdeck.md

Make first-time setup more clear for most users

---

dalamud_troubleshooting.md

@tommadness  has updated his github pages site (https://tommadness.github.io/Plugin-Browser/) to include this list. So replaced the list here with a link and general verbiage.

Update where plogon list

---

development.md

https://github.com/goatcorp/DIPs/issues/27

Add adoption policy

---

dalamud_troubleshooting.md

Friend of mine ran into this issue when she began playing on deck, had to find the answer on Reddit. Thought it would be useful to add here

Add accessing Dalamud with Controller

---

.gitignore
_layouts/default.html
index.md
steamdeck.md

Preview: https://blooym.github.io/faq/

Redo Linux & Steamdeck install guide

---

steamdeck.md

Might need proofreading, I am very tired

docs: snap is buggy + add optional advanced features
